#!/bin/bash

# Prefix commit message with a ticket number automatically. Based on
# https://medium.com/better-programming/how-to-automatically-add-the-ticket-number-in-git-commit-message-bda5426ded05
#
# Examples of ticket numbers that are extracted:
#
# myproj-123-some-feature → MYPROJ-123
# feature/myproj-456-some-other-feature → MYPROJ-456
# bugifx/myproj-789 →  MYPROJ-789
# 123_some_feature →  #123
# 123-another-feature →  #123


FILE=$1
MESSAGE=$(cat $FILE)
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo '^(\w+/)?(\w+[-_])?[0-9]+' | grep -Eo '(\w+[-])?[0-9]+' | tr "[:lower:]" "[:upper:]")
if [[ $TICKET == "" || $TICKET == "develop" || $TICKET == "main" || $TICKET == "master" || $TICKET == "release" || "$MESSAGE" == "$TICKET"*  || "$MESSAGE" == "#$TICKET"* ]];then
  exit 0;
fi

if [[ $TICKET =~ ^[0-9]+$ ]]; then
  TICKET="#$TICKET"
fi

echo "$TICKET $MESSAGE" > $FILE
