#!/bin/bash

# Prefix commit message with a ticket number automatically
# https://medium.com/better-programming/how-to-automatically-add-the-ticket-number-in-git-commit-message-bda5426ded05

FILE=$1
MESSAGE=$(cat $FILE)
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo '^(\w+/)?(\w+[-_])?[0-9]+' | grep -Eo '(\w+[-])?[0-9]+' | tr "[:lower:]" "[:upper:]")
if [[ $TICKET == "" || "$MESSAGE" == "$TICKET"*  || "$MESSAGE" == "#$TICKET"* ]];then
  exit 0;
fi

if [[ $TICKET =~ ^[0-9]+$ ]]; then
  TICKET="#$TICKET"
fi

echo "$TICKET $MESSAGE" > $FILE
